name: Build Executable File

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --noconsole --onefile convert.py

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExcelToTextConverter-Windows
        path: dist/convert.exe

